### PR TITLE
Add awesome-bitclout

### PR DESCRIPTION
**Pull request by BarryMode**
I am requesting an addition of [`awesome-bitclout`](https://github.com/BarryMode/awesome-bitclout), a curated list of awesome BitClout things.

### CODE REVIEW

**Comment by jnv** [comment]
Hi Barry, thanks for the PR!

Could you please adjust the list's description to match contribution guidelines? IMO it would be more helpful to explain in the description what BitClout is (e.g. Blockchain-based crypto social network) since other parts (like "curated list", "resources") are kinda obvious. You can also include a link to BitClout's homepage in the description.

**Comment by BarryMode** [comment]
Thanks @jnv, I'll update it. Good point and sorry for missing one of the guidelines.

**Comment by BarryMode** [comment]
Just to confirm, I did update the description.

**Comment by jnv** [comment]
Sorry @BarryMode, I don't see the updated description in this PR. 🤔 Did you push the change to your fork?

**Pull request merged**
