### PR TITLE
convert list to CSV + script

### PR DESCRIPTION
**Pull request by minimaxir**

### CODE REVIEW

**Comment by minimaxir** [comment]
Looks like GitHub has the same definition for "watchers" and "stargazers". Will fix at some point but can accept PR.

**Comment by jnv** [comment]
Very nice, thanks so much for this, Max! However, I'm a bit hesitant to put this into a main branch, since this would have to be automatically and periodically updated (e.g. with CI tool), which would result in a lot of noise from autogenerated commits. So I'm thinking I could either put the CSV list on a separate branch, or put it into a new repository which would be rebuilt on every commit from this repository. What do you think?

**Comment by qw3rtman** [comment]
A new repository (linked in the README) makes more sense (in my opinion) than a new branch and provides more direct access to the data itself.

**Comment by jnv** [comment]
Perhaps @minimaxir would be interested in setting up a project himself? I could setup webhooks in this project or whatever would be needed.

**Comment by jnv** [comment]
Okay, I have whacked up some setup with [Semaphore CI](https://semaphoreci.com/jnv/lists); it turns out to be actually easier to push on a separate branch with these newfangled CI systems, which don’t even support dependent builds.

You can find the generated CSV on [gh-pages](https://github.com/jnv/lists/tree/gh-pages) branch; it is updated on a daily basis. Maybe I will add some simple webpage for accessing the data in raw form (for now) and JSON export too.

Now I just need to document this stuff.

**Pull request closed without merging**
