### PR TITLE
Adding a better link for awesome-computer-vision

### PR DESCRIPTION
**Pull request by t27**
The newer repository has many more links and many more stars than the currently listed one

### CODE REVIEW

**Comment by jnv** [comment]
Thanks for the suggestion, however could you please add the better repo as a separate entry? You can distinguish between them by adding the username of the respective author, e.g. `[awesome-computer-vision](...) by @jbhuang0604`

**Comment by t27** [comment]
Sure, i'll update the PR

**Comment by koppor** [comment]
The comment has been addressed. Is it possible to merge this PR?

**Comment by jnv** [comment]
@t27 Sorry, I have completely missed your update. I have modified your commit a bit and merged it in b13e973d9aab5632e8bea126ec22aa832442cb20. Thank you!

@koppor Thanks for the heads up!

**Pull request closed without merging**
