### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/CarameloMartins/daemon | https://github.com/caramelomartins/awesome-lint 
https://github.com/Codingbean/Inspire | https://github.com/noahbuscher/Inspire 
https://github.com/EmanueleMinotto/awesome-symfony2 | https://github.com/sitepoint/awesome-symfony 
https://github.com/ITCase/awesome-pyramid | https://github.com/uralbash/awesome-pyramid 
https://github.com/Libertr/libertr | https://github.com/gaapt/libertr 
https://github.com/Pestov/best-of-awesomeness-and-usefuless-for-webdev | https://github.com/Pestov/best-of-awesomeness-and-usefulness-for-webdev 
https://github.com/addyosmani/above-the-fold-css-tools | https://github.com/addyosmani/critical-path-css-tools 
https://github.com/airballoon/awesome-go-books | https://github.com/heatroom/awesome-go-books 
https://github.com/airballoon/awesome-javascript-books | https://github.com/heatroom/awesome-javascript-books 
https://github.com/alexeygolovnya/javascript-resources | https://github.com/ztsu/javascript-resources 
https://github.com/cyberFund/cyberDigest | https://github.com/cyberFund/digest.cyber.fund 
https://github.com/darcyclarke/Front-end-Developer-Interview-Questions | https://github.com/h5bp/Front-end-Developer-Interview-Questions 
https://github.com/deepakbhattarai/awesome-css | https://github.com/bring2dip/awesome-css 
https://github.com/famousky/angularjs-fellows | https://github.com/01010000101001100/angularjs-fellows 
https://github.com/fffaraz/free-programming-courses | https://github.com/fffaraz/MOOC 
https://github.com/floatdrop/awesome-bem | https://github.com/getbem/awesome-bem 
https://github.com/gaearon/redux | https://github.com/rackt/redux 
https://github.com/gillesfabio/awesome-meteor | https://github.com/Urigo/awesome-meteor 
https://github.com/hkalant/EducationalToolsResources | https://github.com/hkalant/awesome-edtech-tools 
https://github.com/instanceofpro/awesome-backbone | https://github.com/sadcitizen/awesome-backbone 
https://github.com/itech001/ciandcd | https://github.com/ciandcd/awesome-ciandcd 
https://github.com/jaspervdj/static-site-generator-comparison | https://github.com/bevry/staticsitegenerators-list 
https://github.com/jdavis/twofactorauth | https://github.com/2factorauth/twofactorauth 
https://github.com/joeljfischer/awesome-objc-swift | https://github.com/joeljfischer/awesome-apple 
https://github.com/lancelafontaine/bioinformatics-tool-list | https://github.com/lancelafontaine/bioinformatics-compbio-tools 
https://github.com/lightSky/MaterialDesignCenter | https://github.com/lightSky/Awesome-MaterialDesign 
https://github.com/mehulkar/github-hall-of-fame | https://github.com/halls-of-fame/github 
https://github.com/onerussell/awesome-derby | https://github.com/russll/awesome-derby 
https://github.com/open-source-society/computer-science-and-engineering | https://github.com/open-source-society/computer-science 
https://github.com/pyotrgalois/spawnedshelter | https://github.com/unbalancedparentheses/spawnedshelter 
https://github.com/reyhoun/awesome-acf | https://github.com/navidkashani/awesome-acf 
https://github.com/sexybiggetje/awesome-linguistics | https://github.com/theimpossibleastronaut/awesome-linguistics 
https://github.com/somecallmejosh/front-end-links | https://github.com/somecallmejosh/front-end-stuff 
https://github.com/strzalek/queues.io | https://github.com/lukaszx0/queues.io 
https://github.com/svaksha/biology | https://github.com/svaksha/aksh 
https://github.com/svaksha/scientia | https://github.com/svaksha/aksh 
https://github.com/therebelrobot/awesome-power-of-5 | https://github.com/therebelbeta/awesome-power-of-5 
https://github.com/vinkla/share-links | https://github.com/vinkla/awesome-share 
https://github.com/weblancaster/awesome-hybrid | https://github.com/weblancaster/awesome-IoT-hybrid 
https://github.com/zhujun2730/android-study_resource-fav | https://github.com/zhujun2730/Android-Learning-Resources 

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://et.wikipedia.org/wiki/Perfokaart | https://et.wikipedia.org/wiki/Perfokaart 
http://learnxinyminutes.com/ | https://learnxinyminutes.com/ 
http://luvit.io/ | https://luvit.io/ 
http://sacha.me/bookmarklets/ | https://sacha.me/bookmarklets/ 
http://staticsitegenerators.net/ | https://staticsitegenerators.net/ 
http://twofactorauth.org/ | https://twofactorauth.org/ 

### Other Corrected URLs 
Was | Now 
--- | --- 
http://bohemiancoding.com/sketch/ | http://www.sketchapp.com/ 
http://mehulkar.com/github-hall-of-fame/ | http://www.mehulkar.com/github-hall-of-fame/ 
https://www.codefellows.org/blog/complete-list-of-javascript-tools | https://www.codefellows.org/blog/a-list-of-foundational-javascript-tools

### CODE REVIEW

**Comment by jnv** [comment]
Very nice, but I'd also need to update descriptions of links and re-sort it all. :frowning:

**Comment by ReadmeCritic** [comment]
Let me give it a try

**Comment by ReadmeCritic** [comment]
@jnv updated

**Comment by jnv** [comment]
Finally got around to merge this. Thank you! :heart:

**Comment by ReadmeCritic** [comment]
:tada:

**Pull request merged**
