### PR TITLE
Fixing link

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @jnv 

just fixing a link.

Cheers!

### CODE REVIEW

**Comment by jnv** [comment]
Thanks! While you are at it, could you please adjust the link to point to `https`? Since this is hosted on github.io, I think that's a more preferable form.

**Comment by spekulatius** [comment]
I could have thought about this myself, sorry. 

It's done now @jnv

**Comment by jnv** [comment]
LGTM, thanks again Peter!

**Comment by spekulatius** [comment]
No worries, happy to help out!

**Pull request merged**
